"""Add sequence_num and year fields

Revision ID: 037e0a00c8ea
Revises: faddabc17ba8
Create Date: 2025-07-28 21:50:33.757334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037e0a00c8ea'
down_revision = 'faddabc17ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter_outgoing', schema=None) as batch_op:
        batch_op.drop_constraint('letter_outgoing_number_seq_key', type_='unique')
        batch_op.drop_column('number_seq')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter_outgoing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_seq', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('letter_outgoing_number_seq_key', ['number_seq'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
