"""Добавлено поле last_active_at для отслеживания активности

Revision ID: 2971790b094e
Revises: 9771911afc64
Create Date: 2025-07-25 16:41:24.366269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2971790b094e'
down_revision = '9771911afc64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_active_at')

    # ### end Alembic commands ###
