"""Add sequence_num and year fields

Revision ID: 61130273c594
Revises: 037e0a00c8ea
Create Date: 2025-07-28 21:53:33.829288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61130273c594'
down_revision = '037e0a00c8ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter_incoming', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence_num', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['sequence_num'])

    with op.batch_alter_table('letter_outgoing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence_num', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['sequence_num'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter_outgoing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('year')
        batch_op.drop_column('sequence_num')

    with op.batch_alter_table('letter_incoming', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('year')
        batch_op.drop_column('sequence_num')

    # ### end Alembic commands ###
