"""Add stored_filename to Attachment

Revision ID: 88871ffe385c
Revises: af8eea952536
Create Date: 2025-07-17 15:29:16.711313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88871ffe385c'
down_revision = 'af8eea952536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stored_filename', sa.String(length=255), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('stored_filename')

    # ### end Alembic commands ###
