"""Add display_name to User

Revision ID: 9deee96b8b27
Revises: 88871ffe385c
Create Date: 2025-07-22 14:00:01.205724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9deee96b8b27'
down_revision = '88871ffe385c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
