"""Добавлено поле is_protected в LetterOutgoing

Revision ID: dd97dd66085f
Revises: 9deee96b8b27
Create Date: 2025-07-23 11:00:18.090110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd97dd66085f'
down_revision = '9deee96b8b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter_outgoing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_protected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter_outgoing', schema=None) as batch_op:
        batch_op.drop_column('is_protected')

    # ### end Alembic commands ###
