"""Add number_seq to LetterOutgoing

Revision ID: faddabc17ba8
Revises: 2971790b094e
Create Date: 2025-07-28 16:06:05.706558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faddabc17ba8'
down_revision = '2971790b094e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter_outgoing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_seq', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['number_seq'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter_outgoing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('number_seq')

    # ### end Alembic commands ###
